const fs = require("fs");
const path = require("path");

/** Remove a directory and all its contents. Returns true on success. */
function rm(dir) {
  if (!fs.existsSync(dir)) return false;
  fs.rmSync(dir, { recursive: true, force: true });
  return true;
}

function clean(dir) {
  if (!fs.existsSync(dir)) return;
  const items = fs.readdirSync(dir);
  for (const name of items) {
    const fp = path.join(dir, name);
    const stat = fs.statSync(fp);
    if (stat.isDirectory()) {
      // Clean the 404/ directory generated by Next.js SSG — EdgeOne
      // handles 404 via its own error page; this file can shadow index.html.
      if (name === "404") {
        rm(fp);
      } else {
        clean(fp);
      }
    } else if (name.endsWith(".txt") || name === "404.html") {
      fs.unlinkSync(fp);
    }
  }
}

clean("out");
